name: Publish Extension

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  CI: true
  AZURE_RESOURCE_GROUP: rg-secretrotation
  AZURE_REGISTRY_NAME: secretrotationbicep
  EXTENSION_NAME: secretrotation
  LOCATION: switzerlandnorth

jobs:
  deploy-acr:
    name: Deploy ACR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: true

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Deploy
        run: |
          az deployment sub create \
            --location ${{ env.LOCATION }} \
            --parameters ./infra/main.bicepparam

  publish-extension:
    needs: deploy-acr
    name: Publish Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Intall Bicep
        run: |
          az config set bicep.use_binary_from_path=false
          az bicep install
      
      - name: Run nbgv
        id: nbgv
        uses: dotnet/nbgv@v0.4.2

      - name: Publish Extension
        run: |
          chmod +x ./infra/scripts/publish.ps1
          target="br:${{ env.AZURE_REGISTRY_NAME }}.azurecr.io/extensions/${{ env.EXTENSION_NAME }}:${{ steps.nbgv.outputs.SimpleVersion }}"
          ./infra/scripts/publish.ps1 -Target $target

          echo "Published extension \`$target\`." >> $GITHUB_STEP_SUMMARY
